#
# Copyright (c) 2023 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

## TODO: @skalldri: remove this
CONFIG_NCS_SAMPLES_DEFAULTS=y

# Enable C++ Language Support
CONFIG_CPLUSPLUS=y

# Enable support for C++20 (HELL YEAH!)
CONFIG_STD_CPP20=y

# Link against the C++ Standard Library
CONFIG_LIB_CPLUSPLUS=y

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="RGB Sunglasses DK"

# Enable the LBS service
CONFIG_BT_NSMS=y

# Enable the NRF DK Button and LED library
#CONFIG_DK_LIBRARY=y

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BOOTLOADER_MCUBOOT=y

CONFIG_MCUBOOT_IMAGE_VERSION="1.2.4"

CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y

CONFIG_NRF53_UPGRADE_NETWORK_CORE=y

CONFIG_ADD_MCUBOOT_MEDIATE_SIM_FLASH_DTS=y

CONFIG_OUTPUT_PRINT_MEMORY_USAGE=y

CONFIG_SPI=y

CONFIG_LED=y

CONFIG_LED_STRIP=y

CONFIG_WS2812_STRIP=y

CONFIG_WS2812_STRIP_SPI=y

CONFIG_STACK_SENTINEL=y

CONFIG_USB_DEVICE_STACK=y

CONFIG_SERIAL=y

CONFIG_CONSOLE=y

CONFIG_UART_CONSOLE=y

CONFIG_UART_LINE_CTRL=y

CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_RUNTIME_FILTERING=y
CONFIG_LOG_BUFFER_SIZE=8192

CONFIG_DEBUG_COREDUMP=y

CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y

# Enable thread performance monitoring
CONFIG_THREAD_MONITOR=y

# Enable the home-built TPS25750 USB Power Delivery controller driver
CONFIG_TPS25750=y

# Need I2C to talk to various components
CONFIG_I2C=y

CONFIG_FLASH=y

# Enable the home-built BQ25792 battery charger driver
CONFIG_BQ25792=y

# Enable a shell that will let us debug the NVM settings
CONFIG_SETTINGS_SHELL=y

# Needed to make LEDs go brr
CONFIG_SPI_ASYNC=y
CONFIG_POLL=y

# Enable the microphone driver
CONFIG_VM3011=y

# Enable the generic PDM / DMIC interface
CONFIG_AUDIO_DMIC=y

#####
### From the Zephyr SMP Bluetooth example
####

# Allow for large Bluetooth data packets.
#CONFIG_BT_L2CAP_TX_MTU=498
#CONFIG_BT_BUF_ACL_RX_SIZE=502
#CONFIG_BT_BUF_ACL_TX_SIZE=502
#CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

# Enable the Bluetooth mcumgr transport (unauthenticated).
CONFIG_MCUMGR_SMP_BT=y
CONFIG_MCUMGR_SMP_BT_AUTHEN=n
CONFIG_MCUMGR_SMP_BT_CONN_PARAM_CONTROL=y

# Enable the Shell mcumgr transport.
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_MCUMGR_SMP_SHELL=y

# Enable the mcumgr Packet Reassembly feature over Bluetooth and its configuration dependencies.
# MCUmgr buffer size is optimized to fit one SMP packet divided into five Bluetooth Write Commands,
# transmitted with the maximum possible MTU value: 498 bytes.
CONFIG_MCUMGR_SMP_REASSEMBLY_BT=y
CONFIG_MCUMGR_BUF_SIZE=2475
CONFIG_OS_MGMT_MCUMGR_PARAMS=y
CONFIG_MCUMGR_SMP_WORKQUEUE_STACK_SIZE=4608

# Enable the LittleFS file system.
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y

# Enable file system commands
CONFIG_MCUMGR_CMD_FS_MGMT=y

# Enable the storage erase command.
CONFIG_MCUMGR_GRP_ZEPHYR_BASIC=y
CONFIG_MCUMGR_GRP_BASIC_CMD_STORAGE_ERASE=y

# Disable Bluetooth ping support
#CONFIG_BT_CTLR_LE_PING=n

# Disable shell commands that are not needed
CONFIG_CLOCK_CONTROL_NRF_SHELL=n
CONFIG_DEVICE_SHELL=n
CONFIG_DEVMEM_SHELL=n
CONFIG_FLASH_SHELL=n