# Use the NRF Secure Immutable Bootloader as the first-stage bootloader for the app core
# See: https://docs.nordicsemi.com/bundle/ncs-3.1.1/page/nrf/samples/bootloader/README.html
# This bootloader is also called "b0"
# SB_CONFIG_SECURE_BOOT_APPCORE=y

# Use MCUboot as the first or second-stage bootload on the app core
# If SB_CONFIG_SECURE_BOOT_APPCORE=y, then this will be the second-stage bootloader
# If SB_CONFIG_SECURE_BOOT_APPCORE=n, then this will be the first-stage bootloader
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Use the NRF Secure Immutable Bootloader as the first-stage bootloader for the network core
# This bootloader is also called "b0n"
SB_CONFIG_SECURE_BOOT_NETCORE=y

# Support network core updates via b0n
SB_CONFIG_NETCORE_APP_UPDATE=y

# Support updating both Network core and Application core via MCUBoot
# This is accomplished by:
# 1) Having a traditional two-slot flash partition reservation for the app
# 2) Reserving the "secondary" slot for the network core in flash. MCUboot writes the in-progress update to 
# 3) Reserving the "primary" slot for the network core in RAM (as "simulated flash"). MCUboot copies the network core image here after it has been validated, 
# and then signals to B0N that the image is ready to be downloaded.
#
# See bootloader\mcuboot\boot\zephyr\pm.yml for details.
SB_CONFIG_MCUBOOT_NRF53_MULTI_IMAGE_UPDATE=y