#pragma once

#include <zephyr/drivers/InternalDeviceRegister.hpp>

/**
 * @brief
 *
 * @tparam reg
 * @tparam registerWidth
 * @tparam U
 * @tparam Us
 */
template <const char *name, uint8_t reg, size_t registerWidth, typename U, typename... Us>
class BQ25792Register : public I2CDeviceRegister<name, reg, registerWidth, U, Us...>
{
    using Base = I2CDeviceRegister<name, reg, registerWidth, U, Us...>;

public:
    BQ25792Register(const struct bq25792_dev_config *cfg) : Base(&(cfg->i2c)) {}
};

// Format:
// #define BQ25792_BIT(_name, _bitLowest, _numBits)


/**
 * Register 0x00 - MINIMAL_SYSTEM_VOLTAGE
 * 
 */
#define BQ25792_REG_MINIMAL_SYSTEM_VOLTAGE_ADDR 0x00
static const char MINIMAL_SYSTEM_VOLTAGE_NAME[] = "MINIMAL_SYSTEM_VOLTAGE";

static const char VSYS_MIN_NAME[] = "VSYS_MIN";
using BQ25792_MINIMAL_SYSTEM_VOLTAGE_VSYS_MIN = RegisterField<VSYS_MIN_NAME, 0, 6>;

using BQ25792_MINIMAL_SYSTEM_VOLTAGE = 
    BQ25792Register<
        MINIMAL_SYSTEM_VOLTAGE_NAME, 
        BQ25792_REG_MINIMAL_SYSTEM_VOLTAGE_ADDR, 
        8,
        BQ25792_MINIMAL_SYSTEM_VOLTAGE_VSYS_MIN>;

/**
 * Register 0x01 - CHARGE_VOLTAGE_LIMIT
 * 
 */
#define BQ25792_REG_CHARGE_VOLTAGE_LIMIT_ADDR 0x01
static const char CHARGE_VOLTAGE_LIMIT_NAME[] = "CHARGE_VOLTAGE_LIMIT";

class BQ25792_CHARGE_VOLTAGE_LIMIT_VREG_UnitConversion
{
public:
    static inline const char *unit()
    {
        return "mV";
    }

    static inline uint32_t conversion(uint32_t val)
    {
        return val * 10;
    }
};
static const char VREG_NAME[] = "VREG";
using BQ25792_CHARGE_VOLTAGE_LIMIT_VREG = RegisterField<VREG_NAME, 0, 11, BQ25792_CHARGE_VOLTAGE_LIMIT_VREG_UnitConversion>;

using BQ25792_CHARGE_VOLTAGE_LIMIT = 
    BQ25792Register<
        CHARGE_VOLTAGE_LIMIT_NAME, 
        BQ25792_REG_CHARGE_VOLTAGE_LIMIT_ADDR, 
        16,
        BQ25792_CHARGE_VOLTAGE_LIMIT_VREG>;

/**
 * Register 0x03 - CHARGE_CURRENT_LIMIT
 * 
 */
#define BQ25792_REG_CHARGE_CURRENT_LIMIT_ADDR 0x03
static const char CHARGE_CURRENT_LIMIT_NAME[] = "CHARGE_CURRENT_LIMIT";

static const char ICHG_NAME[] = "ICHG";
using BQ25792_CHARGE_CURRENT_LIMIT_ICHG = RegisterField<ICHG_NAME, 0, 9>;

using BQ25792_CHARGE_CURRENT_LIMIT = 
    BQ25792Register<
        CHARGE_CURRENT_LIMIT_NAME, 
        BQ25792_REG_CHARGE_CURRENT_LIMIT_ADDR, 
        16,
        BQ25792_CHARGE_CURRENT_LIMIT_ICHG>;

/**
 * Register 0x05 - INPUT_VOLTAGE_LIMIT
 * 
 */
#define BQ25792_REG_INPUT_VOLTAGE_LIMIT_ADDR 0x05
static const char INPUT_VOLTAGE_LIMIT_NAME[] = "INPUT_VOLTAGE_LIMIT";

static const char VINDPM_NAME[] = "VINDPM";
using BQ25792_INPUT_VOLTAGE_LIMIT_VINDPM = RegisterField<VINDPM_NAME, 0, 8>;

using BQ25792_INPUT_VOLTAGE_LIMIT = 
    BQ25792Register<
        INPUT_VOLTAGE_LIMIT_NAME, 
        BQ25792_REG_INPUT_VOLTAGE_LIMIT_ADDR, 
        8,
        BQ25792_INPUT_VOLTAGE_LIMIT_VINDPM>;

/**
 * Register 0x06 - INPUT_CURRENT_LIMIT
 * 
 */
#define BQ25792_REG_INPUT_CURRENT_LIMIT_ADDR 0x06
// Per datasheet, LSB = 10mA
#define BQ25792_REG_INPUT_CURRENT_LIMIT_IINDPM_SCALE 10
static const char INPUT_CURRENT_LIMIT_NAME[] = "INPUT_CURRENT_LIMIT";

static const char IINDPM_NAME[] = "IINDPM";
using BQ25792_INPUT_CURRENT_LIMIT_IINDPM = RegisterField<IINDPM_NAME, 0, 9>;

using BQ25792_INPUT_CURRENT_LIMIT = 
    BQ25792Register<
        INPUT_CURRENT_LIMIT_NAME, 
        BQ25792_REG_INPUT_CURRENT_LIMIT_ADDR, 
        16,
        BQ25792_INPUT_CURRENT_LIMIT_IINDPM>;

/**
 * Register 0x08 - PRECHARGE_CONTROL
 * 
 */
#define BQ25792_REG_PRECHARGE_CONTROL_ADDR 0x08
static const char PRECHARGE_CONTROL_NAME[] = "PRECHARGE_CONTROL";

static const char VBAT_LOWV_NAME[] = "VBAT_LOWV";
using BQ25792_PRECHARGE_CONTROL_VBAT_LOWV = RegisterField<VBAT_LOWV_NAME, 6, 2>;

static const char IPRECHG_NAME[] = "IPRECHG";
using BQ25792_PRECHARGE_CONTROL_IPRECHG = RegisterField<IPRECHG_NAME, 0, 6>;

using BQ25792_PRECHARGE_CONTROL = 
    BQ25792Register<
        PRECHARGE_CONTROL_NAME, 
        BQ25792_REG_PRECHARGE_CONTROL_ADDR, 
        8,
        BQ25792_PRECHARGE_CONTROL_VBAT_LOWV,
        BQ25792_PRECHARGE_CONTROL_IPRECHG>;

/**
 * Register 0x09 - TERMINATION_CONTROL
 * 
 */
#define BQ25792_REG_TERMINATION_CONTROL_ADDR 0x09
static const char TERMINATION_CONTROL_NAME[] = "TERMINATION_CONTROL";

static const char REG_RST_NAME[] = "REG_RST";
using BQ25792_TERMINATION_CONTROL_REG_RST = RegisterField<REG_RST_NAME, 0, 1>;

static const char ITERM_NAME[] = "ITERM";
using BQ25792_TERMINATION_CONTROL_ITERM = RegisterField<ITERM_NAME, 0, 5>;

using BQ25792_TERMINATION_CONTROL = 
    BQ25792Register<
        TERMINATION_CONTROL_NAME, 
        BQ25792_REG_TERMINATION_CONTROL_ADDR, 
        8,
        BQ25792_TERMINATION_CONTROL_REG_RST,
        BQ25792_TERMINATION_CONTROL_ITERM>;

/**
 * Register 0x0A - RECHARGE_CONTROL
 * 
 */
#define BQ25792_REG_RECHARGE_CONTROL_ADDR 0x0A
static const char RECHARGE_CONTROL_NAME[] = "RECHARGE_CONTROL";

static const char CELL_NAME[] = "CELL";
using BQ25792_RECHARGE_CONTROL_CELL = RegisterField<CELL_NAME, 6, 2>;

static const char TRECHG_NAME[] = "TRECHG";
using BQ25792_RECHARGE_CONTROL_TRECHG = RegisterField<TRECHG_NAME, 4, 2>;

static const char VRECHG_NAME[] = "VRECHG";
using BQ25792_RECHARGE_CONTROL_VRECHG = RegisterField<VRECHG_NAME, 0, 4>;

using BQ25792_RECHARGE_CONTROL = 
    BQ25792Register<
        RECHARGE_CONTROL_NAME, 
        BQ25792_REG_RECHARGE_CONTROL_ADDR, 
        8,
        BQ25792_RECHARGE_CONTROL_CELL,
        BQ25792_RECHARGE_CONTROL_TRECHG,
        BQ25792_RECHARGE_CONTROL_VRECHG>;

/**
 * Register 0x0B - VOTG_REGULATION
 * 
 */
#define BQ25792_REG_VOTG_REGULATION_ADDR 0x0B
static const char VOTG_REGULATION_NAME[] = "VOTG_REGULATION";

static const char VOTG_NAME[] = "VOTG";
using BQ25792_VOTG_REGULATION_VOTG = RegisterField<VOTG_NAME, 0, 11>;

using BQ25792_VOTG_REGULATION = 
    BQ25792Register<
        VOTG_REGULATION_NAME, 
        BQ25792_REG_VOTG_REGULATION_ADDR, 
        16,
        BQ25792_VOTG_REGULATION_VOTG>;

/**
 * Register 0x0D - IOTG_REGULATION
 * 
 */

#define BQ25792_REG_IOTG_REGULATION_ADDR 0x0D
static const char IOTG_REGULATION_NAME[] = "IOTG_REGULATION";

static const char PRECHG_TIMER_NAME[] = "PRECHG_TIMER";
using BQ25792_IOTG_REGULATION_PRECHG_TIMER = RegisterField<PRECHG_TIMER_NAME, 7, 1>;

static const char IOTG_NAME[] = "IOTG";
using BQ25792_IOTG_REGULATION_IOTG = RegisterField<IOTG_NAME, 0, 7>;

using BQ25792_IOTG_REGULATION = 
    BQ25792Register<
        IOTG_REGULATION_NAME, 
        BQ25792_REG_IOTG_REGULATION_ADDR, 
        8,
        BQ25792_IOTG_REGULATION_PRECHG_TIMER,
        BQ25792_IOTG_REGULATION_IOTG>;

/**
 * Register 0x0E - TIMER_CONTROL
 * 
 */

#define BQ25792_REG_TIMER_CONTROL_ADDR 0x0E
static const char TIMER_CONTROL_NAME[] = "TIMER_CONTROL";

static const char TOPOFF_TMR_NAME[] = "TOPOFF_TMR";
using BQ25792_TIMER_CONTROL_TOPOFF_TMR = RegisterField<TOPOFF_TMR_NAME, 6, 2>;

static const char EN_TRICHG_TMR_NAME[] = "EN_TRICHG_TMR";
using BQ25792_TIMER_CONTROL_EN_TRICHG_TMR = RegisterField<EN_TRICHG_TMR_NAME, 5, 1>;

static const char EN_PRECHG_TMR_NAME[] = "EN_PRECHG_TMR";
using BQ25792_TIMER_CONTROL_EN_PRECHG_TMR = RegisterField<EN_PRECHG_TMR_NAME, 4, 1>;

static const char EN_CHG_TMR_NAME[] = "EN_CHG_TMR";
using BQ25792_TIMER_CONTROL_EN_CHG_TMR = RegisterField<EN_CHG_TMR_NAME, 3, 1>;

static const char CHG_TMR_NAME[] = "CHG_TMR";
using BQ25792_TIMER_CONTROL_CHG_TMR = RegisterField<CHG_TMR_NAME, 1, 2>;

static const char TMR2X_EN_NAME[] = "TMR2X_EN";
using BQ25792_TIMER_CONTROL_TMR2X_EN = RegisterField<TMR2X_EN_NAME, 0, 1>;

using BQ25792_TIMER_CONTROL = 
    BQ25792Register<
        TIMER_CONTROL_NAME, 
        BQ25792_REG_TIMER_CONTROL_ADDR,
        8,
        BQ25792_TIMER_CONTROL_TOPOFF_TMR,
        BQ25792_TIMER_CONTROL_EN_TRICHG_TMR,
        BQ25792_TIMER_CONTROL_EN_PRECHG_TMR,
        BQ25792_TIMER_CONTROL_EN_CHG_TMR,
        BQ25792_TIMER_CONTROL_CHG_TMR,
        BQ25792_TIMER_CONTROL_TMR2X_EN>;

/**
 * Register 0x0F - CHARGER_CONTROL_0
 * 
 */

#define BQ25792_REG_CHARGER_CONTROL_0_ADDR 0x0F

#define BQ25792_REG_CHARGER_CONTROL_0_BITS \
    BQ25792_BIT(EN_AUTO_IBATDIS, 7, 1)     \
    BQ25792_BIT(FORCE_IBATDIS, 6, 1)       \
    BQ25792_BIT(EN_CHG, 5, 1)              \
    BQ25792_BIT(EN_ICO, 4, 1)              \
    BQ25792_BIT(FORCE_ICO, 3, 1)           \
    BQ25792_BIT(EN_HIZ, 2, 1)              \
    BQ25792_BIT(EN_TERM, 1, 1)

static const char CHARGER_CONTROL_0_NAME[] = "CHARGER_CONTROL_0";

static const char EN_AUTO_IBATDIS_NAME[] = "EN_AUTO_IBATDIS";
using BQ25792_CHARGER_CONTROL_0_EN_AUTO_IBATDIS = RegisterField<EN_AUTO_IBATDIS_NAME, 7, 1>;

static const char FORCE_IBATDIS_NAME[] = "FORCE_IBATDIS";
using BQ25792_CHARGER_CONTROL_0_FORCE_IBATDIS = RegisterField<FORCE_IBATDIS_NAME, 6, 1>;

static const char EN_CHG_NAME[] = "EN_CHG";
using BQ25792_CHARGER_CONTROL_0_EN_CHG = RegisterField<EN_CHG_NAME, 5, 1>;

static const char EN_ICO_NAME[] = "EN_ICO";
using BQ25792_CHARGER_CONTROL_0_EN_ICO = RegisterField<EN_ICO_NAME, 4, 1>;

static const char FORCE_ICO_NAME[] = "FORCE_ICO";
using BQ25792_CHARGER_CONTROL_0_FORCE_ICO = RegisterField<FORCE_ICO_NAME, 3, 1>;

static const char EN_HIZ_NAME[] = "EN_HIZ";
using BQ25792_CHARGER_CONTROL_0_EN_HIZ = RegisterField<EN_HIZ_NAME, 2, 1>;

static const char EN_TERM_NAME[] = "EN_TERM";
using BQ25792_CHARGER_CONTROL_0_EN_TERM = RegisterField<EN_TERM_NAME, 1, 1>;

using BQ25792_CHARGER_CONTROL_0 = 
    BQ25792Register<
        CHARGER_CONTROL_0_NAME, 
        BQ25792_REG_CHARGER_CONTROL_0_ADDR,
        8,
        BQ25792_CHARGER_CONTROL_0_EN_AUTO_IBATDIS,
        BQ25792_CHARGER_CONTROL_0_FORCE_IBATDIS,
        BQ25792_CHARGER_CONTROL_0_EN_CHG,
        BQ25792_CHARGER_CONTROL_0_EN_ICO,
        BQ25792_CHARGER_CONTROL_0_FORCE_ICO,
        BQ25792_CHARGER_CONTROL_0_EN_HIZ,
        BQ25792_CHARGER_CONTROL_0_EN_TERM>;

/**
 * Register 0x10 - CHARGER_CONTROL_1
 * 
 */

#define BQ25792_REG_CHARGER_CONTROL_1_ADDR 0x10

#define BQ25792_REG_CHARGER_CONTROL_1_BITS \
    BQ25792_BIT(VAC_OVP, 4, 2)             \
    BQ25792_BIT(WD_RST, 3, 1)              \
    BQ25792_BIT(WATCHDOG, 0, 2)

static const char CHARGER_CONTROL_1_NAME[] = "CHARGER_CONTROL_1";

static const char VAC_OVP_NAME[] = "VAC_OVP";
using BQ25792_CHARGER_CONTROL_1_VAC_OVP = RegisterField<VAC_OVP_NAME, 4, 2>;

static const char WD_RST_NAME[] = "WD_RST";
using BQ25792_CHARGER_CONTROL_1_WD_RST = RegisterField<WD_RST_NAME, 3, 1>;

static const char WATCHDOG_NAME[] = "WATCHDOG";
using BQ25792_CHARGER_CONTROL_1_WATCHDOG = RegisterField<WATCHDOG_NAME, 0, 2>;

using BQ25792_CHARGER_CONTROL_1 = 
    BQ25792Register<
        CHARGER_CONTROL_1_NAME, 
        BQ25792_REG_CHARGER_CONTROL_1_ADDR,
        8,
        BQ25792_CHARGER_CONTROL_1_VAC_OVP,
        BQ25792_CHARGER_CONTROL_1_WD_RST,
        BQ25792_CHARGER_CONTROL_1_WATCHDOG>;


/**
 * Register 0x11 - CHARGER_CONTROL_2
 * 
 */
#define BQ25792_REG_CHARGER_CONTROL_2_ADDR 0x11

#define BQ25792_REG_CHARGER_CONTROL_2_BITS \
    BQ25792_BIT(FORCE_INDET, 7, 1)         \
    BQ25792_BIT(AUTO_INDET_EN, 6, 1)       \
    BQ25792_BIT(EN_12V, 5, 1)              \
    BQ25792_BIT(EN_9V, 4, 1)               \
    BQ25792_BIT(HVDCP_EN, 3, 1)            \
    BQ25792_BIT(SDRV_CTRL, 1, 2)           \
    BQ25792_BIT(SDRV_DLY, 0, 1)

static const char CHARGER_CONTROL_2_NAME[] = "CHARGER_CONTROL_2";

static const char FORCE_INDET_NAME[] = "FORCE_INDET";
using BQ25792_CHARGER_CONTROL_2_FORCE_INDET = RegisterField<FORCE_INDET_NAME, 7, 1>;

static const char AUTO_INDET_EN_NAME[] = "AUTO_INDET_EN";
using BQ25792_CHARGER_CONTROL_2_AUTO_INDET_EN = RegisterField<AUTO_INDET_EN_NAME, 6, 1>;

static const char EN_12V_NAME[] = "EN_12V";
using BQ25792_CHARGER_CONTROL_2_EN_12V = RegisterField<EN_12V_NAME, 5, 1>;

static const char EN_9V_NAME[] = "EN_9V";
using BQ25792_CHARGER_CONTROL_2_EN_9V = RegisterField<EN_9V_NAME, 4, 1>;

static const char HVDCP_EN_NAME[] = "HVDCP_EN";
using BQ25792_CHARGER_CONTROL_2_HVDCP_EN = RegisterField<HVDCP_EN_NAME, 3, 1>;

static const char SDRV_CTRL_NAME[] = "SDRV_CTRL";
using BQ25792_CHARGER_CONTROL_2_SDRV_CTRL = RegisterField<SDRV_CTRL_NAME, 1, 2>;

static const char SDRV_DLY_NAME[] = "SDRV_DLY";
using BQ25792_CHARGER_CONTROL_2_SDRV_DLY = RegisterField<SDRV_DLY_NAME, 0, 1>;

using BQ25792_CHARGER_CONTROL_2 = 
    BQ25792Register<
        CHARGER_CONTROL_2_NAME, 
        BQ25792_REG_CHARGER_CONTROL_2_ADDR,
        8,
        BQ25792_CHARGER_CONTROL_2_FORCE_INDET,
        BQ25792_CHARGER_CONTROL_2_AUTO_INDET_EN,
        BQ25792_CHARGER_CONTROL_2_EN_12V,
        BQ25792_CHARGER_CONTROL_2_EN_9V,
        BQ25792_CHARGER_CONTROL_2_HVDCP_EN,
        BQ25792_CHARGER_CONTROL_2_SDRV_CTRL,
        BQ25792_CHARGER_CONTROL_2_SDRV_DLY>;


/**
 * Register 0x12 - CHARGER_CONTROL_3
 * 
 */

#define BQ25792_REG_CHARGER_CONTROL_3_ADDR 0x12

#define BQ25792_REG_CHARGER_CONTROL_3_BITS \
    BQ25792_BIT(DIS_ACDRV, 7, 1)           \
    BQ25792_BIT(EN_OTG, 6, 1)              \
    BQ25792_BIT(PFM_OTG_DIS, 5, 1)         \
    BQ25792_BIT(PFM_FWD_DIS, 4, 1)         \
    BQ25792_BIT(WKUP_DLY, 3, 1)            \
    BQ25792_BIT(DIS_LDO, 2, 1)             \
    BQ25792_BIT(DIS_OTG_OOA, 1, 1)         \
    BQ25792_BIT(DIS_FWD_OOA, 0, 1)

static const char CHARGER_CONTROL_3_NAME[] = "CHARGER_CONTROL_3";

static const char DIS_ACDRV_NAME[] = "DIS_ACDRV";
using BQ25792_CHARGER_CONTROL_3_DIS_ACDRV = RegisterField<DIS_ACDRV_NAME, 7, 1>;

static const char EN_OTG_NAME[] = "EN_OTG";
using BQ25792_CHARGER_CONTROL_3_EN_OTG = RegisterField<EN_OTG_NAME, 6, 1>;

static const char PFM_OTG_DIS_NAME[] = "PFM_OTG_DIS";
using BQ25792_CHARGER_CONTROL_3_PFM_OTG_DIS = RegisterField<PFM_OTG_DIS_NAME, 5, 1>;

static const char PFM_FWD_DIS_NAME[] = "PFM_FWD_DIS";
using BQ25792_CHARGER_CONTROL_3_PFM_FWD_DIS = RegisterField<PFM_FWD_DIS_NAME, 4, 1>;

static const char WKUP_DLY_NAME[] = "WKUP_DLY";
using BQ25792_CHARGER_CONTROL_3_WKUP_DLY = RegisterField<WKUP_DLY_NAME, 3, 1>;

static const char DIS_LDO_NAME[] = "DIS_LDO";
using BQ25792_CHARGER_CONTROL_3_DIS_LDO = RegisterField<DIS_LDO_NAME, 2, 1>;

static const char DIS_OTG_OOA_NAME[] = "DIS_OTG_OOA";
using BQ25792_CHARGER_CONTROL_3_DIS_OTG_OOA = RegisterField<DIS_OTG_OOA_NAME, 1, 1>;

static const char DIS_FWD_OOA_NAME[] = "DIS_FWD_OOA";
using BQ25792_CHARGER_CONTROL_3_DIS_FWD_OOA = RegisterField<DIS_FWD_OOA_NAME, 0, 1>;

using BQ25792_CHARGER_CONTROL_3 = 
    BQ25792Register<
        CHARGER_CONTROL_3_NAME, 
        BQ25792_REG_CHARGER_CONTROL_3_ADDR,
        8,
        BQ25792_CHARGER_CONTROL_3_DIS_ACDRV,
        BQ25792_CHARGER_CONTROL_3_EN_OTG,
        BQ25792_CHARGER_CONTROL_3_PFM_OTG_DIS,
        BQ25792_CHARGER_CONTROL_3_PFM_FWD_DIS,
        BQ25792_CHARGER_CONTROL_3_WKUP_DLY,
        BQ25792_CHARGER_CONTROL_3_DIS_LDO,
        BQ25792_CHARGER_CONTROL_3_DIS_OTG_OOA,
        BQ25792_CHARGER_CONTROL_3_DIS_FWD_OOA>;

/**
 * Register 0x13 - CHARGER_CONTROL_4
 * 
 */

#define BQ25792_REG_CHARGER_CONTROL_4_ADDR 0x13

#define BQ25792_REG_CHARGER_CONTROL_4_BITS \
    BQ25792_BIT(EN_ACDRV2, 7, 1)           \
    BQ25792_BIT(EN_ACDRV1, 6, 1)           \
    BQ25792_BIT(PWM_FREQ, 5, 1)            \
    BQ25792_BIT(DIS_STAT, 4, 1)            \
    BQ25792_BIT(DIS_VSYS_SHORT, 3, 1)      \
    BQ25792_BIT(DIS_VOTG_UVP, 2, 1)        \
    BQ25792_BIT(FORCE_VINDPM_DET, 1, 1)    \
    BQ25792_BIT(EN_IBUS_OCP, 0, 1)

static const char CHARGER_CONTROL_4_NAME[] = "CHARGER_CONTROL_4";

static const char EN_ACDRV2_NAME[] = "EN_ACDRV2";
using BQ25792_CHARGER_CONTROL_4_EN_ACDRV2 = RegisterField<EN_ACDRV2_NAME, 7, 1>;

static const char EN_ACDRV1_NAME[] = "EN_ACDRV1";
using BQ25792_CHARGER_CONTROL_4_EN_ACDRV1 = RegisterField<EN_ACDRV1_NAME, 6, 1>;

static const char PWM_FREQ_NAME[] = "PWM_FREQ";
using BQ25792_CHARGER_CONTROL_4_PWM_FREQ = RegisterField<PWM_FREQ_NAME, 5, 1>;

static const char DIS_STAT_NAME[] = "DIS_STAT";
using BQ25792_CHARGER_CONTROL_4_DIS_STAT = RegisterField<DIS_STAT_NAME, 4, 1>;

static const char DIS_VSYS_SHORT_NAME[] = "DIS_VSYS_SHORT";
using BQ25792_CHARGER_CONTROL_4_DIS_VSYS_SHORT = RegisterField<DIS_VSYS_SHORT_NAME, 3, 1>;

static const char DIS_VOTG_UVP_NAME[] = "DIS_VOTG_UVP";
using BQ25792_CHARGER_CONTROL_4_DIS_VOTG_UVP = RegisterField<DIS_VOTG_UVP_NAME, 2, 1>;

static const char FORCE_VINDPM_DET_NAME[] = "FORCE_VINDPM_DET";
using BQ25792_CHARGER_CONTROL_4_FORCE_VINDPM_DET = RegisterField<FORCE_VINDPM_DET_NAME, 1, 1>;

static const char EN_IBUS_OCP_NAME[] = "EN_IBUS_OCP";
using BQ25792_CHARGER_CONTROL_4_EN_IBUS_OCP = RegisterField<EN_IBUS_OCP_NAME, 0, 1>;

using BQ25792_CHARGER_CONTROL_4 = 
    BQ25792Register<
        CHARGER_CONTROL_4_NAME, 
        BQ25792_REG_CHARGER_CONTROL_4_ADDR,
        8,
        BQ25792_CHARGER_CONTROL_4_EN_ACDRV2,
        BQ25792_CHARGER_CONTROL_4_EN_ACDRV1,
        BQ25792_CHARGER_CONTROL_4_PWM_FREQ,
        BQ25792_CHARGER_CONTROL_4_DIS_STAT,
        BQ25792_CHARGER_CONTROL_4_DIS_VSYS_SHORT,
        BQ25792_CHARGER_CONTROL_4_DIS_VOTG_UVP,
        BQ25792_CHARGER_CONTROL_4_FORCE_VINDPM_DET,
        BQ25792_CHARGER_CONTROL_4_EN_IBUS_OCP>;

/**
 * Register 0x14 - CHARGER_CONTROL_5
 * 
 */

#define BQ25792_REG_CHARGER_CONTROL_5_ADDR 0x14

#define BQ25792_REG_CHARGER_CONTROL_5_BITS \
    BQ25792_BIT(SFET_PRESENT, 7, 1)        \
    BQ25792_BIT(EN_IBAT, 5, 1)             \
    BQ25792_BIT(IBAT_REG, 3, 2)            \
    BQ25792_BIT(EN_IINDPM, 2, 1)           \
    BQ25792_BIT(EN_EXTILIM, 1, 1)          \
    BQ25792_BIT(EN_BATOC, 0, 1)

static const char CHARGER_CONTROL_5_NAME[] = "CHARGER_CONTROL_5";

static const char SFET_PRESENT_NAME[] = "SFET_PRESENT";
using BQ25792_CHARGER_CONTROL_5_SFET_PRESENT = RegisterField<SFET_PRESENT_NAME, 7, 1>;

static const char EN_IBAT_NAME[] = "EN_IBAT";
using BQ25792_CHARGER_CONTROL_5_EN_IBAT = RegisterField<EN_IBAT_NAME, 5, 1>;

static const char IBAT_REG_NAME[] = "IBAT_REG";
using BQ25792_CHARGER_CONTROL_5_IBAT_REG = RegisterField<IBAT_REG_NAME, 3, 1>;

static const char EN_IINDPM_NAME[] = "EN_IINDPM";
using BQ25792_CHARGER_CONTROL_5_EN_IINDPM = RegisterField<EN_IINDPM_NAME, 2, 1>;

static const char EN_EXTILIM_NAME[] = "EN_EXTILIM";
using BQ25792_CHARGER_CONTROL_5_EN_EXTILIM = RegisterField<EN_EXTILIM_NAME, 1, 1>;

static const char EN_BATOC_NAME[] = "EN_BATOC";
using BQ25792_CHARGER_CONTROL_5_EN_BATOC = RegisterField<EN_BATOC_NAME, 0, 1>;

using BQ25792_CHARGER_CONTROL_5 = 
    BQ25792Register<
        CHARGER_CONTROL_5_NAME, 
        BQ25792_REG_CHARGER_CONTROL_5_ADDR,
        8,
        BQ25792_CHARGER_CONTROL_5_SFET_PRESENT,
        BQ25792_CHARGER_CONTROL_5_EN_IBAT,
        BQ25792_CHARGER_CONTROL_5_IBAT_REG,
        BQ25792_CHARGER_CONTROL_5_EN_IINDPM,
        BQ25792_CHARGER_CONTROL_5_EN_EXTILIM,
        BQ25792_CHARGER_CONTROL_5_EN_BATOC>;

/**
 * Register 0x16 - TEMPERATURE_CONTROL
 * 
 */

#define BQ25792_REG_TEMPERATURE_CONTROL_ADDR 0x16
static const char TEMPERATURE_CONTROL_NAME[] = "TEMPERATURE_CONTROL";

static const char TREG_NAME[] = "TREG";
using BQ25792_TEMPERATURE_CONTROL_TREG = RegisterField<TREG_NAME, 6, 2>;

static const char TSHUT_NAME[] = "TSHUT";
using BQ25792_TEMPERATURE_CONTROL_TSHUT = RegisterField<TSHUT_NAME, 4, 2>;

static const char VBUS_PD_EN_NAME[] = "VBUS_PD_EN";
using BQ25792_TEMPERATURE_CONTROL_VBUS_PD_EN = RegisterField<VBUS_PD_EN_NAME, 3, 1>;

static const char VAC1_PD_EN_NAME[] = "VAC1_PD_EN";
using BQ25792_TEMPERATURE_CONTROL_VAC1_PD_EN = RegisterField<VAC1_PD_EN_NAME, 2, 1>;

static const char VAC2_PD_EN_NAME[] = "VAC2_PD_EN";
using BQ25792_TEMPERATURE_CONTROL_VAC2_PD_EN = RegisterField<VAC2_PD_EN_NAME, 1, 1>;

using BQ25792_TEMPERATURE_CONTROL = 
    BQ25792Register<
        TEMPERATURE_CONTROL_NAME, 
        BQ25792_REG_TEMPERATURE_CONTROL_ADDR,
        8,
        BQ25792_TEMPERATURE_CONTROL_TREG,
        BQ25792_TEMPERATURE_CONTROL_TSHUT,
        BQ25792_TEMPERATURE_CONTROL_VBUS_PD_EN,
        BQ25792_TEMPERATURE_CONTROL_VAC1_PD_EN,
        BQ25792_TEMPERATURE_CONTROL_VAC2_PD_EN>;

/**
 * Register 0x17 - NTC_CONTROL_0
 * 
 */

#define BQ25792_REG_NTC_CONTROL_0_ADDR 0x17
static const char NTC_CONTROL_0_NAME[] = "NTC_CONTROL_0";

#define BQ25792_REG_NTC_CONTROL_0_BITS \
    BQ25792_BIT(JEITA_VSET, 5, 3)      \
    BQ25792_BIT(JEITA_ISETH, 3, 2)     \
    BQ25792_BIT(JEITA_ISETC, 1, 2)

static const char JEITA_VSET_NAME[] = "JEITA_VSET";
using BQ25792_NTC_CONTROL_0_JEITA_VSET = RegisterField<JEITA_VSET_NAME, 5, 3>;

static const char JEITA_ISETH_NAME[] = "JEITA_ISETH";
using BQ25792_NTC_CONTROL_0_JEITA_ISETH = RegisterField<JEITA_ISETH_NAME, 3, 2>;

static const char JEITA_ISETC_NAME[] = "JEITA_ISETC";
using BQ25792_NTC_CONTROL_0_JEITA_ISETC = RegisterField<JEITA_ISETC_NAME, 1, 2>;

using BQ25792_NTC_CONTROL_0 = 
    BQ25792Register<
        NTC_CONTROL_0_NAME, 
        BQ25792_REG_NTC_CONTROL_0_ADDR,
        8,
        BQ25792_NTC_CONTROL_0_JEITA_VSET,
        BQ25792_NTC_CONTROL_0_JEITA_ISETH,
        BQ25792_NTC_CONTROL_0_JEITA_ISETC>;

/**
 * Register 0x18 - NTC_CONTROL_1
 * 
 */

#define BQ25792_REG_NTC_CONTROL_1_ADDR 0x18
static const char NTC_CONTROL_1_NAME[] = "NTC_CONTROL_1";

#define BQ25792_REG_NTC_CONTROL_1_BITS \
    BQ25792_BIT(TS_COOL, 6, 2)         \
    BQ25792_BIT(TS_WARM, 4, 2)         \
    BQ25792_BIT(BHOT, 2, 2)            \
    BQ25792_BIT(BCOLD, 1, 1)           \
    BQ25792_BIT(TS_IGNORE, 0, 1)

static const char TS_COOL_NAME[] = "TS_COOL";
using BQ25792_NTC_CONTROL_1_TS_COOL = RegisterField<TS_COOL_NAME, 6, 2>;

static const char TS_WARM_NAME[] = "TS_WARM";
using BQ25792_NTC_CONTROL_1_TS_WARM = RegisterField<TS_WARM_NAME, 4, 2>;

static const char BHOT_NAME[] = "BHOT";
using BQ25792_NTC_CONTROL_1_BHOT = RegisterField<BHOT_NAME, 2, 2>;

static const char BCOLD_NAME[] = "BCOLD";
using BQ25792_NTC_CONTROL_1_BCOLD = RegisterField<BCOLD_NAME, 1, 1>;

static const char TS_IGNORE_NAME[] = "TS_IGNORE";
using BQ25792_NTC_CONTROL_1_TS_IGNORE = RegisterField<TS_IGNORE_NAME, 0, 1>;

using BQ25792_NTC_CONTROL_1 = 
    BQ25792Register<
        NTC_CONTROL_1_NAME, 
        BQ25792_REG_NTC_CONTROL_1_ADDR,
        8,
        BQ25792_NTC_CONTROL_1_TS_COOL,
        BQ25792_NTC_CONTROL_1_TS_WARM,
        BQ25792_NTC_CONTROL_1_BHOT,
        BQ25792_NTC_CONTROL_1_BCOLD,
        BQ25792_NTC_CONTROL_1_TS_IGNORE>;

/**
 * Register 0x19 - ICO_CURRENT_LIMIT
 * 
 */

#define BQ25792_REG_ICO_CURRENT_LIMIT_ADDR 0x19
static const char ICO_CURRENT_LIMIT_NAME[] = "ICO_CURRENT_LIMIT";

// Per datasheet, LSB = 10mA
#define BQ25792_REG_ICO_CURRENT_LIMIT_ICO_ILIM_SCALE 10

static const char ICO_ILIM_NAME[] = "ICO_ILIM";
using BQ25792_ICO_CURRENT_LIMIT_ICO_ILIM = RegisterField<ICO_ILIM_NAME, 0, 9>;

using BQ25792_ICO_CURRENT_LIMIT = 
    BQ25792Register<
        ICO_CURRENT_LIMIT_NAME, 
        BQ25792_REG_ICO_CURRENT_LIMIT_ADDR,
        16,
        BQ25792_ICO_CURRENT_LIMIT_ICO_ILIM>;

/**
 * Register 0x1B - CHARGER_STATUS_0
 * 
 */
#define BQ25792_REG_CHARGER_STATUS_0_ADDR 0x1B
static const char CHARGER_STATUS_0_NAME[] = "CHARGER_STATUS_0";

#define BQ25792_REG_CHARGER_STATUS_0_BITS \
    BQ25792_BIT(IINDPM_STAT, 7, 1)        \
    BQ25792_BIT(VINDPM_STAT, 6, 1)        \
    BQ25792_BIT(WD_STAT, 5, 1)            \
    BQ25792_BIT(POORSRC_STAT, 4, 1)       \
    BQ25792_BIT(PG_STAT, 3, 1)            \
    BQ25792_BIT(AC2_PRESENT_STAT, 2, 1)   \
    BQ25792_BIT(AC1_PRESENT_STAT, 1, 1)   \
    BQ25792_BIT(VBUS_PRESENT_STAT, 0, 1)

static const char IINDPM_STAT_NAME[] = "IINDPM_STAT";
using BQ25792_CHARGER_STATUS_0_IINDPM_STAT = RegisterField<IINDPM_STAT_NAME, 7, 1>;

static const char VINDPM_STAT_NAME[] = "VINDPM_STAT";
using BQ25792_CHARGER_STATUS_0_VINDPM_STAT = RegisterField<VINDPM_STAT_NAME, 6, 1>;

static const char WD_STAT_NAME[] = "WD_STAT";
using BQ25792_CHARGER_STATUS_0_WD_STAT = RegisterField<WD_STAT_NAME, 5, 1>;

static const char POORSRC_STAT_NAME[] = "POORSRC_STAT";
using BQ25792_CHARGER_STATUS_0_POORSRC_STAT = RegisterField<POORSRC_STAT_NAME, 4, 1>;

static const char PG_STAT_NAME[] = "PG_STAT";
using BQ25792_CHARGER_STATUS_0_PG_STAT = RegisterField<PG_STAT_NAME, 3, 1>;

static const char AC2_PRESENT_STAT_NAME[] = "AC2_PRESENT_STAT";
using BQ25792_CHARGER_STATUS_0_AC2_PRESENT_STAT = RegisterField<AC2_PRESENT_STAT_NAME, 2, 1>;

static const char AC1_PRESENT_STAT_NAME[] = "AC1_PRESENT_STAT";
using BQ25792_CHARGER_STATUS_0_AC1_PRESENT_STAT = RegisterField<AC1_PRESENT_STAT_NAME, 1, 1>;

static const char VBUS_PRESENT_STAT_NAME[] = "VBUS_PRESENT_STAT";
using BQ25792_CHARGER_STATUS_0_VBUS_PRESENT_STAT = RegisterField<VBUS_PRESENT_STAT_NAME, 0, 1>;

using BQ25792_CHARGER_STATUS_0 = 
    BQ25792Register<
        CHARGER_STATUS_0_NAME, 
        BQ25792_REG_CHARGER_STATUS_0_ADDR, 
        8,
        BQ25792_CHARGER_STATUS_0_IINDPM_STAT,
        BQ25792_CHARGER_STATUS_0_VINDPM_STAT,
        BQ25792_CHARGER_STATUS_0_WD_STAT,
        BQ25792_CHARGER_STATUS_0_POORSRC_STAT,
        BQ25792_CHARGER_STATUS_0_PG_STAT,
        BQ25792_CHARGER_STATUS_0_AC2_PRESENT_STAT,
        BQ25792_CHARGER_STATUS_0_AC1_PRESENT_STAT,
        BQ25792_CHARGER_STATUS_0_VBUS_PRESENT_STAT>;

/**
 * Register 0x1C - CHARGER_STATUS_1
 * 
 */
#define BQ25792_REG_CHARGER_STATUS_1_ADDR 0x1C
static const char CHARGER_STATUS_1_NAME[] = "CHARGER_STATUS_1";

#define BQ25792_REG_CHARGER_STATUS_1_BITS \
    BQ25792_BIT(CHG_STAT, 5, 3)           \
    BQ25792_BIT(VBUS_STAT, 1, 4)          \
    BQ25792_BIT(BC1_2_DONE_STAT, 1, 1)

static const char CHG_STAT_NAME[] = "CHG_STAT";
using BQ25792_CHARGER_STATUS_1_CHG_STAT = RegisterField<CHG_STAT_NAME, 5, 3>;

static const char VBUS_STAT_NAME[] = "VBUS_STAT";
using BQ25792_CHARGER_STATUS_1_VBUS_STAT = RegisterField<VBUS_STAT_NAME, 1, 4>;

static const char BC1_2_DONE_STAT_NAME[] = "BC1_2_DONE_STAT";
using BQ25792_CHARGER_STATUS_1_BC1_2_DONE_STAT = RegisterField<BC1_2_DONE_STAT_NAME, 1, 1>;

using BQ25792_CHARGER_STATUS_1 = 
    BQ25792Register<
        CHARGER_STATUS_1_NAME, 
        BQ25792_REG_CHARGER_STATUS_1_ADDR, 
        8,
        BQ25792_CHARGER_STATUS_1_CHG_STAT,
        BQ25792_CHARGER_STATUS_1_VBUS_STAT,
        BQ25792_CHARGER_STATUS_1_BC1_2_DONE_STAT>;

/**
 * Register 0x1D - CHARGER_STATUS_2
 * 
 */
#define BQ25792_REG_CHARGER_STATUS_2_ADDR 0x1D
static const char CHARGER_STATUS_2_NAME[] = "CHARGER_STATUS_2";

#define BQ25792_REG_CHARGER_STATUS_2_BITS \
    BQ25792_BIT(ICO_STAT, 6, 2)           \
    BQ25792_BIT(TREG_STAT, 2, 1)          \
    BQ25792_BIT(DPDM_STAT, 1, 1)          \
    BQ25792_BIT(VBAT_PRESENT_STAT, 0, 1)

static const char ICO_STAT_NAME[] = "ICO_STAT";
using BQ25792_CHARGER_STATUS_2_ICO_STAT = RegisterField<ICO_STAT_NAME, 6, 2>;

static const char TREG_STAT_NAME[] = "TREG_STAT";
using BQ25792_CHARGER_STATUS_2_TREG_STAT = RegisterField<TREG_STAT_NAME, 2, 1>;

static const char DPDM_STAT_NAME[] = "DPDM_STAT";
using BQ25792_CHARGER_STATUS_2_DPDM_STAT = RegisterField<DPDM_STAT_NAME, 1, 1>;

static const char VBAT_PRESENT_STAT_NAME[] = "VBAT_PRESENT_STAT";
using BQ25792_CHARGER_STATUS_2_VBAT_PRESENT_STAT = RegisterField<VBAT_PRESENT_STAT_NAME, 0, 1>;

using BQ25792_CHARGER_STATUS_2 = 
    BQ25792Register<
        CHARGER_STATUS_2_NAME, 
        BQ25792_REG_CHARGER_STATUS_2_ADDR, 
        8,
        BQ25792_CHARGER_STATUS_2_ICO_STAT,
        BQ25792_CHARGER_STATUS_2_TREG_STAT,
        BQ25792_CHARGER_STATUS_2_DPDM_STAT,
        BQ25792_CHARGER_STATUS_2_VBAT_PRESENT_STAT>;

/**
 * Register 0x1E - CHARGER_STATUS_3
 * 
 */
#define BQ25792_REG_CHARGER_STATUS_3_ADDR 0x1E

#define BQ25792_REG_CHARGER_STATUS_3_BITS \
    BQ25792_BIT(ACRB2_STAT, 7, 1)         \
    BQ25792_BIT(ACRB1_STAT, 6, 1)         \
    BQ25792_BIT(ADC_DONE_STAT, 5, 1)      \
    BQ25792_BIT(VSYS_STAT, 4, 1)          \
    BQ25792_BIT(CHG_TMR_STAT, 3, 1)       \
    BQ25792_BIT(TRICHG_TMR_STAT, 2, 1)    \
    BQ25792_BIT(PRECHG_TMR_STAT, 1, 1)

static const char CHARGER_STATUS_3_NAME[] = "CHARGER_STATUS_3";

static const char ACRB2_STAT_NAME[] = "ACRB2_STAT";
using BQ25792_CHARGER_STATUS_3_ACRB2_STAT = RegisterField<ACRB2_STAT_NAME, 7, 1>;

static const char ACRB1_STAT_NAME[] = "ACRB1_STAT";
using BQ25792_CHARGER_STATUS_3_ACRB1_STAT = RegisterField<ACRB1_STAT_NAME, 6, 1>;

static const char ADC_DONE_STAT_NAME[] = "ADC_DONE_STAT";
using BQ25792_CHARGER_STATUS_3_ADC_DONE_STAT = RegisterField<ADC_DONE_STAT_NAME, 5, 1>;

static const char VSYS_STAT_NAME[] = "VSYS_STAT";
using BQ25792_CHARGER_STATUS_3_VSYS_STAT = RegisterField<VSYS_STAT_NAME, 4, 1>;

static const char CHG_TMR_STAT_NAME[] = "CHG_TMR_STAT";
using BQ25792_CHARGER_STATUS_3_CHG_TMR_STAT = RegisterField<CHG_TMR_STAT_NAME, 3, 1>;

static const char TRICHG_TMR_STAT_NAME[] = "TRICHG_TMR_STAT";
using BQ25792_CHARGER_STATUS_3_TRICHG_TMR_STAT = RegisterField<TRICHG_TMR_STAT_NAME, 2, 1>;

static const char PRECHG_TMR_STAT_NAME[] = "PRECHG_TMR_STAT";
using BQ25792_CHARGER_STATUS_3_PRECHG_TMR_STAT = RegisterField<PRECHG_TMR_STAT_NAME, 1, 1>;

using BQ25792_CHARGER_STATUS_3 = 
    BQ25792Register<
        CHARGER_STATUS_3_NAME, 
        BQ25792_REG_CHARGER_STATUS_3_ADDR, 
        8,
        BQ25792_CHARGER_STATUS_3_ACRB2_STAT,
        BQ25792_CHARGER_STATUS_3_ACRB1_STAT,
        BQ25792_CHARGER_STATUS_3_ADC_DONE_STAT,
        BQ25792_CHARGER_STATUS_3_VSYS_STAT,
        BQ25792_CHARGER_STATUS_3_CHG_TMR_STAT,
        BQ25792_CHARGER_STATUS_3_TRICHG_TMR_STAT,
        BQ25792_CHARGER_STATUS_3_PRECHG_TMR_STAT>;

/**
 * Register 0x1F - CHARGER_STATUS_4
 * 
 */
#define BQ25792_REG_CHARGER_STATUS_4_ADDR 0x1F

#define BQ25792_REG_CHARGER_STATUS_4_BITS \
    BQ25792_BIT(VBATOTG_LOW_STAT, 4, 1)   \
    BQ25792_BIT(TS_COLD_STAT, 3, 1)       \
    BQ25792_BIT(TS_COOL_STAT, 2, 1)       \
    BQ25792_BIT(TS_WARM_STAT, 1, 1)       \
    BQ25792_BIT(TS_HOT_STAT, 0, 1)

static const char CHARGER_STATUS_4_NAME[] = "CHARGER_STATUS_4";

static const char VBATOTG_LOW_STAT_NAME[] = "VBATOTG_LOW_STAT";
using BQ25792_CHARGER_STATUS_4_VBATOTG_LOW_STAT = RegisterField<VBATOTG_LOW_STAT_NAME, 4, 1>;

static const char TS_COLD_STAT_NAME[] = "TS_COLD_STAT";
using BQ25792_CHARGER_STATUS_4_TS_COLD_STAT = RegisterField<TS_COLD_STAT_NAME, 3, 1>;

static const char TS_COOL_STAT_NAME[] = "TS_COOL_STAT";
using BQ25792_CHARGER_STATUS_4_TS_COOL_STAT = RegisterField<TS_COOL_STAT_NAME, 2, 1>;

static const char TS_WARM_STAT_NAME[] = "TS_WARM_STAT";
using BQ25792_CHARGER_STATUS_4_TS_WARM_STAT = RegisterField<TS_WARM_STAT_NAME, 1, 1>;

static const char TS_HOT_STAT_NAME[] = "TS_HOT_STAT";
using BQ25792_CHARGER_STATUS_4_TS_HOT_STAT = RegisterField<TS_HOT_STAT_NAME, 0, 1>;

using BQ25792_CHARGER_STATUS_4 = 
    BQ25792Register<
        CHARGER_STATUS_4_NAME, 
        BQ25792_REG_CHARGER_STATUS_4_ADDR, 
        8,
        BQ25792_CHARGER_STATUS_4_VBATOTG_LOW_STAT,
        BQ25792_CHARGER_STATUS_4_TS_COLD_STAT,
        BQ25792_CHARGER_STATUS_4_TS_COOL_STAT,
        BQ25792_CHARGER_STATUS_4_TS_WARM_STAT,
        BQ25792_CHARGER_STATUS_4_TS_HOT_STAT>;

/**
 * Register 0x20 - FAULT_STATUS_0
 * 
 */
#define BQ25792_REG_FAULT_STATUS_0_ADDR 0x20

#define BQ25792_REG_FAULT_STATUS_0_BITS \
    BQ25792_BIT(IBAT_REG_STAT, 7, 1)    \
    BQ25792_BIT(VBUS_OVP_STAT, 6, 1)    \
    BQ25792_BIT(VBAT_OVP_STAT, 5, 1)    \
    BQ25792_BIT(IBUS_OCP_STAT, 4, 1)    \
    BQ25792_BIT(IBAT_OCP_STAT, 3, 1)    \
    BQ25792_BIT(CONV_OCP_STAT, 2, 1)    \
    BQ25792_BIT(VAC2_OVP_STAT, 1, 1)    \
    BQ25792_BIT(VAC1_OVP_STAT, 0, 1)

static const char FAULT_STATUS_0_NAME[] = "FAULT_STATUS_0";

static const char IBAT_REG_STAT_NAME[] = "IBAT_REG_STAT";
using BQ25792_FAULT_STATUS_0_IBAT_REG_STAT = RegisterField<IBAT_REG_STAT_NAME, 7, 1>;

static const char VBUS_OVP_STAT_NAME[] = "VBUS_OVP_STAT";
using BQ25792_FAULT_STATUS_0_VBUS_OVP_STAT = RegisterField<VBUS_OVP_STAT_NAME, 6, 1>;

static const char VBAT_OVP_STAT_NAME[] = "VBAT_OVP_STAT";
using BQ25792_FAULT_STATUS_0_VBAT_OVP_STAT = RegisterField<VBAT_OVP_STAT_NAME, 5, 1>;

static const char IBUS_OCP_STAT_NAME[] = "IBUS_OCP_STAT";
using BQ25792_FAULT_STATUS_0_IBUS_OCP_STAT = RegisterField<IBUS_OCP_STAT_NAME, 4, 1>;

static const char IBAT_OCP_STAT_NAME[] = "IBAT_OCP_STAT";
using BQ25792_FAULT_STATUS_0_IBAT_OCP_STAT = RegisterField<IBAT_OCP_STAT_NAME, 3, 1>;

static const char CONV_OCP_STAT_NAME[] = "CONV_OCP_STAT";
using BQ25792_FAULT_STATUS_0_CONV_OCP_STAT = RegisterField<CONV_OCP_STAT_NAME, 2, 1>;

static const char VAC2_OVP_STAT_NAME[] = "VAC2_OVP_STAT";
using BQ25792_FAULT_STATUS_0_VAC2_OVP_STAT = RegisterField<VAC2_OVP_STAT_NAME, 1, 1>;

static const char VAC1_OVP_STAT_NAME[] = "VAC1_OVP_STAT";
using BQ25792_FAULT_STATUS_0_VAC1_OVP_STAT = RegisterField<VAC1_OVP_STAT_NAME, 0, 1>;

using BQ25792_FAULT_STATUS_0 = 
    BQ25792Register<
        FAULT_STATUS_0_NAME, 
        BQ25792_REG_FAULT_STATUS_0_ADDR, 
        8,
        BQ25792_FAULT_STATUS_0_IBAT_REG_STAT,
        BQ25792_FAULT_STATUS_0_VBUS_OVP_STAT,
        BQ25792_FAULT_STATUS_0_VBAT_OVP_STAT,
        BQ25792_FAULT_STATUS_0_IBUS_OCP_STAT,
        BQ25792_FAULT_STATUS_0_IBAT_OCP_STAT,
        BQ25792_FAULT_STATUS_0_CONV_OCP_STAT,
        BQ25792_FAULT_STATUS_0_VAC2_OVP_STAT,
        BQ25792_FAULT_STATUS_0_VAC1_OVP_STAT>;

/**
 * Register 0x21 - FAULT_STATUS_1
 * 
 */
#define BQ25792_REG_FAULT_STATUS_1_ADDR 0x21

#define BQ25792_REG_FAULT_STATUS_1_BITS \
    BQ25792_BIT(VSYS_SHORT_STAT, 7, 1)  \
    BQ25792_BIT(VSYS_OVP_STAT, 6, 1)    \
    BQ25792_BIT(OTG_OVP_STAT, 5, 1)     \
    BQ25792_BIT(OTG_UVP_STAT, 4, 1)     \
    BQ25792_BIT(TSHUT_STAT, 2, 1)

static const char FAULT_STATUS_1_NAME[] = "FAULT_STATUS_1";

static const char VSYS_SHORT_STAT_NAME[] = "VSYS_SHORT_STAT";
using BQ25792_FAULT_STATUS_1_VSYS_SHORT_STAT = RegisterField<VSYS_SHORT_STAT_NAME, 7, 1>;

static const char VSYS_OVP_STAT_NAME[] = "VSYS_OVP_STAT";
using BQ25792_FAULT_STATUS_1_VSYS_OVP_STAT = RegisterField<VSYS_OVP_STAT_NAME, 6, 1>;

static const char OTG_OVP_STAT_NAME[] = "OTG_OVP_STAT";
using BQ25792_FAULT_STATUS_1_OTG_OVP_STAT = RegisterField<OTG_OVP_STAT_NAME, 5, 1>;

static const char OTG_UVP_STAT_NAME[] = "OTG_UVP_STAT";
using BQ25792_FAULT_STATUS_1_OTG_UVP_STAT = RegisterField<OTG_UVP_STAT_NAME, 4, 1>;

static const char TSHUT_STAT_NAME[] = "TSHUT_STAT";
using BQ25792_FAULT_STATUS_1_TSHUT_STAT = RegisterField<TSHUT_STAT_NAME, 2, 1>;

using BQ25792_FAULT_STATUS_1 = 
    BQ25792Register<
        FAULT_STATUS_1_NAME, 
        BQ25792_REG_FAULT_STATUS_1_ADDR, 
        8,
        BQ25792_FAULT_STATUS_1_VSYS_SHORT_STAT,
        BQ25792_FAULT_STATUS_1_VSYS_OVP_STAT,
        BQ25792_FAULT_STATUS_1_OTG_OVP_STAT,
        BQ25792_FAULT_STATUS_1_OTG_UVP_STAT,
        BQ25792_FAULT_STATUS_1_TSHUT_STAT>;


#define REG_LIST                       \
    REG(BQ25792_REG_CHARGER_CONTROL_0) \
    REG(BQ25792_REG_CHARGER_CONTROL_1) \
    REG(BQ25792_REG_CHARGER_CONTROL_2) \
    REG(BQ25792_REG_CHARGER_CONTROL_3) \
    REG(BQ25792_REG_CHARGER_CONTROL_4) \
    REG(BQ25792_REG_CHARGER_CONTROL_5) \
    REG(BQ25792_REG_NTC_CONTROL_0)     \
    REG(BQ25792_REG_NTC_CONTROL_1)     \
    REG(BQ25792_REG_CHARGER_STATUS_0)  \
    REG(BQ25792_REG_CHARGER_STATUS_1)  \
    REG(BQ25792_REG_CHARGER_STATUS_2)  \
    REG(BQ25792_REG_CHARGER_STATUS_3)  \
    REG(BQ25792_REG_CHARGER_STATUS_4)  \
    REG(BQ25792_REG_FAULT_STATUS_0)    \
    REG(BQ25792_REG_FAULT_STATUS_1)

/* If this baby hits 88 mph... you're gonna see some serious shit */

#define BQ25792_BIT(_name, _bitLowest, _numBits) \
    uint8_t _name;

#define REG(_regName)       \
    typedef struct _regName \
    {                       \
        uint8_t raw;        \
        _regName##_BITS     \
    } _regName##_t;

REG_LIST

#undef REG
#undef BQ25792_BIT