# Use the NRF Secure Immutable Bootloader as the first-stage bootloader for the app core
# See: https://docs.nordicsemi.com/bundle/ncs-3.1.1/page/nrf/samples/bootloader/README.html
# This bootloader is also called "b0"
# SB_CONFIG_SECURE_BOOT_APPCORE=y

# Use MCUboot as the first or second-stage bootload on the app core
# If SB_CONFIG_SECURE_BOOT_APPCORE=y, then this will be the second-stage bootloader
# If SB_CONFIG_SECURE_BOOT_APPCORE=n, then this will be the first-stage bootloader
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Use the NRF Secure Immutable Bootloader as the first-stage bootloader for the network core
# This bootloader is also called "b0n"
SB_CONFIG_SECURE_BOOT_NETCORE=y

# Support network core updates via b0n
SB_CONFIG_NETCORE_APP_UPDATE=y

# Support updating both Network core and Application core via MCUBoot
# This is accomplished by:
# 1) Having a traditional two-slot flash partition reservation for the app
# 2) Reserving the "secondary" slot for the network core in flash. MCUboot writes the in-progress update to 
# 3) Reserving the "primary" slot for the network core in RAM (as "simulated flash"). MCUboot copies the network core image here after it has been validated, 
# and then signals to B0N that the image is ready to be downloaded.
#
# See bootloader\mcuboot\boot\zephyr\pm.yml for details.
SB_CONFIG_MCUBOOT_NRF53_MULTI_IMAGE_UPDATE=y

# The default MCUBoot upgrade mode is "swap". Unfortunately we cannot use this mode. Why?
# The main app does indeed support "swap" mode: MCUboot can swap the primary and secondary images, since 
# they both reside in flash that is accessible to the app-core bootloader.
#
# The network core however is special, and does not support "swap" mode.
# Recall that the "true" primary image for the network core resides in the network-core's flash, which is innaccessible to the app core.
# The secondary image for the network core resides in the app-core's flash.
# A "fake" primary image is created in RAM (via a simulated flash driver). When MCUboot performs the network core update it 
# copies the network-core secondary image into the "fake" primary image. A post-update hook then signals the B0N bootloader to copy
# the update image from the "fake" primary image into the "true" primary image.
# 
# The "swap" upgrade mode requires direct access to the "true" primary image so that it can be backed-up into the secondary image slot. MCUboot cannot read 
# the "true" primary image from the network core. There is no way to tell MCUboot that 
# it should use "swap" for the application, and "move" mode for the network core.
# Thus, we must use "move" mode (aka "overwrite only" mode) for both core's images.
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y
