/**
 * Tests for the Audio Param Ranges blob decoder.
 *
 * As with the telemetry codec, the decisive test is the one against bytes the FIRMWARE
 * produced. Regenerate after any table or format change (from the repo root):
 *
 *   g++ -std=c++2b -I fw/src -I fw/src/sound -o /tmp/gen_blob fw/tools/gen_param_blob_vector.cpp
 *   /tmp/gen_blob > app/__tests__/fixtures/audio-param-ranges-vector.json
 */

import vector from "./fixtures/audio-param-ranges-vector.json";
import {
  AUDIO_PARAM_BLOB_VERSION,
  parseAudioParamRanges,
} from "@/services/audio-param-ranges";
import {
  AUDIO_PARAMS,
  AUDIO_PARAM_ORDER,
  resolveAudioParams,
  noiseLevelFromGate,
  sensitivityFromAlpha,
  type AudioParamKey,
} from "@/services/audio-params";

type Vector = {
  size: number;
  bytes: number[];
  expect: {
    key: string;
    label: string;
    type: number;
    unit: string;
    def: number;
    min: number;
    max: number;
    step: number;
  }[];
};

const V = vector as Vector;

function toBase64(bytes: number[]): string {
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s);
}

const FIRMWARE_BLOB = toBase64(V.bytes);

describe("parseAudioParamRanges — against firmware-generated bytes", () => {
  it("decodes the real blob", () => {
    const out = parseAudioParamRanges(FIRMWARE_BLOB);
    expect(out).not.toBeNull();
    expect(Object.keys(out!)).toHaveLength(AUDIO_PARAM_ORDER.length);
  });

  it("recovers every range exactly as the firmware table declares it", () => {
    const out = parseAudioParamRanges(FIRMWARE_BLOB)!;
    AUDIO_PARAM_ORDER.forEach((key, i) => {
      const want = V.expect[i];
      const got = out[key]!;
      expect(got).toBeDefined();
      expect(got.min).toBeCloseTo(want.min, 9);
      expect(got.max).toBeCloseTo(want.max, 9);
      expect(got.defaultValue).toBeCloseTo(want.def, 9);
    });
  });

  it("agrees with the app-side table the sliders currently use", () => {
    // If this ever fails, the app's mirror of the firmware clamps has drifted — which is the
    // exact failure the blob exists to make impossible, so it should be loud.
    //
    // Compared at FLOAT32 precision, not exactly. The firmware stores these as float32, so
    // 0.08 arrives as 0.07999999821186066 and an exact comparison fails on every parameter
    // whose decimal literal is not representable — which is most of them. That gap is real but
    // it is not drift: both encode to the identical four bytes on the wire, and it is ~5e-8
    // relative against the 2% tolerance the macro inverses use, so no pill control can flip to
    // "Custom" because of it.
    const out = parseAudioParamRanges(FIRMWARE_BLOB)!;
    for (const key of AUDIO_PARAM_ORDER) {
      const app = AUDIO_PARAMS[key];
      const fw = out[key]!;
      expect([key, fw.min]).toEqual([key, Math.fround(app.min)]);
      expect([key, fw.max]).toEqual([key, Math.fround(app.max)]);
      expect([key, fw.defaultValue]).toEqual([
        key,
        Math.fround(app.defaultValue),
      ]);
    }
  });

  it("stays inside the macro inverses tolerance, so pills do not flip to Custom", () => {
    // The concrete worry: applying firmware defaults could make a device sitting exactly on a
    // macro step read as "Custom" because of float32 rounding. It cannot — but that is a
    // property worth pinning rather than re-deriving next time someone changes the tolerance.
    const out = parseAudioParamRanges(FIRMWARE_BLOB)!;
    expect(noiseLevelFromGate(out.agcNoiseGateRms!.defaultValue!)).toBe(
      noiseLevelFromGate(AUDIO_PARAMS.agcNoiseGateRms.defaultValue),
    );
    expect(sensitivityFromAlpha(out.beatAlpha!.defaultValue!)).toBe(
      sensitivityFromAlpha(AUDIO_PARAMS.beatAlpha.defaultValue),
    );
  });

  it("maps blob position to parameter by GATT declaration order", () => {
    // The blob is positional; a reordering here would silently apply the wrong range to every
    // parameter, all of them plausible-looking.
    V.expect.forEach((entry, i) => {
      expect(AUDIO_PARAMS[AUDIO_PARAM_ORDER[i]].firmwareLabel).toBe(
        entry.label,
      );
    });
  });

  it("carries enum labels only for the enum parameter", () => {
    const out = parseAudioParamRanges(FIRMWARE_BLOB)!;
    const withLabels = AUDIO_PARAM_ORDER.filter((k) => out[k]?.enumLabels);
    expect(withLabels).toEqual(["beatThresholdMode"]);
    expect(out.beatThresholdMode!.enumLabels!.length).toBeGreaterThanOrEqual(2);
  });
});

describe("parseAudioParamRanges — refusals", () => {
  it("refuses an unknown version rather than guessing at the layout", () => {
    const bad = [...V.bytes];
    bad[0] = AUDIO_PARAM_BLOB_VERSION + 1;
    expect(parseAudioParamRanges(toBase64(bad))).toBeNull();
  });


  it("decodes the known prefix of a NEWER firmware's longer table", () => {
    // audio_param_table.h is append-only, so a future firmware with a 15th tunable sends
    // count = 15. Refusing that outright made every already-shipped app fall back to its own
    // table for all 14 parameters it DID know — recreating the retuned-after-ship staleness
    // (beat_alpha 3.5 -> 0.3) this blob exists to prevent.
    const extended = [...V.bytes];
    extended[1] = AUDIO_PARAM_ORDER.length + 1;
    // A plausible 15th entry: float type, no unit, no enum labels, four float32s.
    extended.push(0, 0, 0, ...new Array(16).fill(0));

    const out = parseAudioParamRanges(toBase64(extended));
    expect(out).not.toBeNull();
    expect(Object.keys(out!)).toHaveLength(AUDIO_PARAM_ORDER.length);
    // The prefix still decodes correctly — this is the whole point.
    expect(out!.beatAlpha!.min).toBeCloseTo(V.expect[2].min, 6);
  });

  it("decodes the prefix an OLDER firmware's shorter table sends", () => {
    // First reachable in the field when the table grew 14 -> 17 (the FFT Bars dB mapping):
    // a newer app on fw-v3.8.1 gets count = 14. Its 14 entries are still the same trusted
    // prefix, and refusing them dropped the device-authoritative ranges for every parameter
    // the app DID share with that firmware. The three missing keys are simply absent, as
    // resolveAudioParams() already tolerates for absent characteristics.
    const short = [...V.bytes];
    const knownCount = AUDIO_PARAM_ORDER.length - 3;
    short[1] = knownCount;

    const out = parseAudioParamRanges(toBase64(short));
    expect(out).not.toBeNull();
    expect(Object.keys(out!)).toHaveLength(knownCount);
    for (const key of AUDIO_PARAM_ORDER.slice(0, knownCount)) {
      expect(out![key]).toBeDefined();
    }
    for (const key of AUDIO_PARAM_ORDER.slice(knownCount)) {
      expect(out![key]).toBeUndefined();
    }
    expect(out!.beatAlpha!.min).toBeCloseTo(V.expect[2].min, 6);
  });

  it("refuses an empty table", () => {
    const empty = [...V.bytes];
    empty[1] = 0;
    expect(parseAudioParamRanges(toBase64(empty))).toBeNull();
  });

  it("refuses a truncated blob rather than applying a partial result", () => {
    // A partial decode is the dangerous outcome: some firmware ranges, some app guesses, a
    // mixture nobody designed.
    for (const cut of [2, 20, V.bytes.length - 1]) {
      expect(parseAudioParamRanges(toBase64(V.bytes.slice(0, cut)))).toBeNull();
    }
  });

  it("refuses an inverted or empty range", () => {
    const out = parseAudioParamRanges(FIRMWARE_BLOB)!;
    expect(out).not.toBeNull();
    // Corrupt the first entry's max to equal its min.
    const bad = [...V.bytes];
    const firstEntryMinAt = 2 + 1 + (1 + V.expect[0].unit.length) + 1 + 4;
    for (let k = 0; k < 4; k++)
      bad[firstEntryMinAt + 4 + k] = bad[firstEntryMinAt + k];
    expect(parseAudioParamRanges(toBase64(bad))).toBeNull();
  });

  it("is null-safe", () => {
    expect(parseAudioParamRanges(null)).toBeNull();
    expect(parseAudioParamRanges(undefined)).toBeNull();
    expect(parseAudioParamRanges("")).toBeNull();
    expect(parseAudioParamRanges(toBase64([]))).toBeNull();
  });

  it("ignores bytes after the final entry", () => {
    const padded = [...V.bytes, 9, 9, 9];
    const out = parseAudioParamRanges(toBase64(padded));
    expect(out).not.toBeNull();
    expect(Object.keys(out!)).toHaveLength(AUDIO_PARAM_ORDER.length);
  });
});

describe("overrides applied through resolveAudioParams", () => {
  it("a firmware range replaces the app-side one", () => {
    // The point of the whole feature: the device's own clamps win, so a slider cannot offer a
    // value the firmware would reject.
    const key: AudioParamKey = "beatAlpha";
    const spec = AUDIO_PARAMS[key];
    const chars = { [spec.uuid]: { value: null } };
    const resolved = resolveAudioParams(chars, {
      [key]: { min: 0.5, max: 5, defaultValue: 1 },
    });
    const entry = resolved.find((r) => r.spec.key === key)!;
    expect(entry.spec.min).toBe(0.5);
    expect(entry.spec.max).toBe(5);
    expect(entry.spec.defaultValue).toBe(1);
    // Everything not overridden is preserved.
    expect(entry.spec.friendlyLabel).toBe(spec.friendlyLabel);
    expect(entry.spec.help).toBe(spec.help);
  });
});
